#! /usr/bin/env python3
import requests
from bs4 import BeautifulSoup
import string

#Plus de "Le wifi" compris ? Maintenant que tu as appris UN texte, j'aimerais que tu en récupère PLEIN !
#Voici le lien de la page wikipédia de du Championnat d'islande de football en 1982 (oui), https://fr.wikipedia.org/wiki/Championnat_d%27Islande_de_football_1982
#J'aimerais que tu récupère tout les lien de la pages, et que tu puisses me les afficher !
#ATTENTION, je veux seulement les liens commençant par /wiki/ !
