#! /usr/bin/env python3

import requests
from bs4 import BeautifulSoup
import re

# Bon désolé mais t'es beaucoup trop fort, je met cette exo pour te stop.
#Voici le lien de base : https://www.grandsgites.com/grand-gite-alsace.htm
#je souhaite que tu me récupère tout les noms de gites, et leur addresse correspondant. Il y'a un exemple dans le dossier
#bonne chance :D
#PS: c'est normal si ton script met du temps, requests c'est long :)
