#! /usr/bin/env python3

import requests
from bs4 import BeautifulSoup
import re

# Bon désolé mais t'es beaucoup trop fort, je met cette exo pour te stop.
#Voici le lien de base : https://www.grandsgites.com/grand-gite-alsace.htm
#je souhaite que tu me récupère tout les noms de gites, et leur addresse correspondant. Il y'a un exemple dans le dossier
#bonne chance :D
#PS: c'est normal si ton script met du temps, requests c'est long :)

r = requests.get('https://www.grandsgites.com/grand-gite-alsace.htm')
soup = BeautifulSoup(r.content, 'html.parser')
tmp = soup.find_all('a')
pattern = "<a href=\"(.*(gite-(67|68)).*)\" title=\".*\">"
finalLink = []
for i in tmp:
    matches = re.findall(pattern, str(i))
    if matches:
        finalLink.append(matches[0][0])
register = []
checker = 0
for shelter in finalLink:
    url = 'https://www.grandsgites.com/' + shelter
    r = requests.get(url)
    soup = BeautifulSoup(r.content, 'html.parser')
    elem = soup.find('div', attrs= {'id' : 'bloc_pres_annonce'})
    title = elem.get_text().splitlines()[1]
    adressNotFormated = elem.get_text().splitlines()[2].split('/')[0].split(' - ')
    adressNotFormated = [i.strip() for i in adressNotFormated]
    if (len(adressNotFormated) == 3):
        adressFormated = adressNotFormated[0].replace(',', "") + ', ' + adressNotFormated[1].split()[1] + ', ' + adressNotFormated[2]
        for adress in register:
            if adressNotFormated[0] in adress:
                adressFormated = adress
                break
        register.append((title, adressFormated))
        checker = 0

lst_set = set(register)
register = list(lst_set)
for i in register:
    print(f'{i[0]};{i[1]}')