#! /usr/bin/env python3
import requests
from bs4 import BeautifulSoup

# Trop fort ! Retiens bien l'ex2, c'est un outil magique qui nous servira plus tard !
# Maintenant, j'aimerais que tu puises me trouver un texte en particulier de nouveau, mais sur une page plus complexe !
#Voici le lien de la page wikipédia de Epitech, https://fr.wikipedia.org/wiki/%C3%89cole_pour_l%27informatique_et_les_nouvelles_technologies
# J'aimerais que tu récupère les localisations des différents Epitech, qui sont localisés dans le beau tableau à droite :) !
# Format attendu :
# Ville1
# Ville2
# ...
