#! /usr/bin/env python3
import requests
from bs4 import BeautifulSoup
import re

#Allez, on passe au niveau 1 du scrapping. Voici le lien racine : https://supermarches.grandes-enseignes.com/67-bas-rhin/
#Sur cette page, on peut accéder à toute les communes bas-rhin avec un lien.
#J'aimerais que vous m'affichiez tout les titres d'onglets de chacune des pages.
#Bonne chance :)

