#! /usr/bin/env python3
import requests
from bs4 import BeautifulSoup
import re

#Allez, on passe au niveau 1 du scrapping. Voici le lien racine : https://supermarches.grandes-enseignes.com/67-bas-rhin/
#Sur cette page, on peut accéder à toute les communes bas-rhin avec un lien.
#J'aimerais que vous m'affichiez tout les titres d'onglets de chacune des pages.
#Bonne chance :)

url = "https://supermarches.grandes-enseignes.com/67-bas-rhin/"
r = requests.get(url)
soup = BeautifulSoup(r.content, 'html.parser')
tmp = soup.find_all('a')
finalLink = []
for elem in tmp:
    try:
        finalLink.append(elem.get('href').split('/')[2])
    except:
        continue
for market in finalLink:
    r = requests.get(url + market)
    soup = BeautifulSoup(r.content, 'html.parser')
    print(soup.title.text)