#! /usr/bin/env python3
import requests
from bs4 import BeautifulSoup
import re

#Allez, on passe au niveau 1 du scrapping. Voici le lien racine : https://www.randogps.net/randonnee-pedestre-gps-bas-rhin-strasbourg-67.php
#Sur cette page, on peut accéder à toute les communes bas-rhin avec un lien.
#J'aimerais que vous m'affichiez tout les titres d'onglets de chacune des pages.
#Bonne chance :)

url = "https://www.randogps.net/randonnee-pedestre-gps-bas-rhin-strasbourg-67.php"
r = requests.get(url)
soup = BeautifulSoup(r.content, 'html.parser')
tmp = soup.find_all('a')
finalLink = []
for elem in tmp:
    try:
        finalLink.append(elem.get('href'))
    except:
        continue
for hike in finalLink:
    r = requests.get("https://www.randogps.net/" + hike)
    soup = BeautifulSoup(r.content, 'html.parser')
    print(soup.title.text)