#! /usr/bin/env python3
from bs4 import BeautifulSoup
import pandas as pd
import requests

#Monsieur est déjà un expert enfaite ! On va utiliser une nouvelle libairie supplémentaire cette fois-ci, Pandas !
#J'aimerais que tu me créer un fichier, "world_population_by_country.csv", en prenant de base la page wikipédia
# suivante : https://fr.wikipedia.org/wiki/Liste_des_pays_par_population.
# Le CSV serait composé de 4 colonne. Le classement, le pays, la population au 1er janvier 2021, et la population estimé en 2023.

url = 'https://fr.wikipedia.org/wiki/Liste_des_pays_par_population'
response = requests.get(url)
soup = BeautifulSoup(response.text, 'html.parser')
data = soup.find('table')
df = pd.read_html(str(data))[0]
df.head()
df.describe()
df.to_csv(r"world_population_by_country.csv", index = None, header = True)