#! /usr/bin/env python3
import requests
from bs4 import BeautifulSoup

#Parfait maintenant nous pouvons vraiment commencer avec cette première étape : ta première soupe !
#Si tu veux jouer le jeu pour cette exercice, essaye de ne pas ouvrir le lien, tu gagneras rien mais ce sera marrant !
#Voici le lien de la page wikipédia de l'histoire de la wifi, https://www.lawifi.fr/
#J'aimerais que tu récupère le contenu de la balise h1 et que tu m'affiche le texte contenu !
